include ../d3.make

install:barchart.css barchart.js data.tsv index.html
	cp barchart.css barchart.js data.tsv index.html $(WEBDIR)

unstall:
	rm -rf $(WEBDIR)/barchart.css $(WEBDIR)/barchart.js $(WEBDIR)/data.tsv $(xWEBDIR)/index.html
